# Generated by Django 3.1.1 on 2020-09-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calorie',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
