# Generated by Django 3.1.1 on 2020-09-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_user_fat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
